In [1]:
import numpy as np

In [13]:
bin_arr = np.array([[0,0,1,0,1],
                      [1,1,1,0,0],
                      [0,0,1,0,1],
                      [1,1,0,0,1]])

In [20]:
def dfs(bin_arr, index_arr, i, j, cur_index):
    stack = [(i,j)]
    (N1,N2) = bin_arr.shape
    while len(stack)> 0:
        (x,y) = stack.pop()
        index_arr[x,y] = cur_index
        if (x < N1 -1) and (bin_arr[x+1,y] == 1) and (index_arr[x+1,y] < 0):
            stack.append((x+1,y))
        if (y < N2 - 1) and (bin_arr[x,y+1] == 1) and (index_arr[x,y+1] < 0):
            stack.append((x,y+1))
        if (x > 0) and (bin_arr[x-1,y] == 1) and (index_arr[x-1,y] < 0):
            stack.append((x-1,y))
        if (y > 0) and (bin_arr[x,y-1] == 1) and (index_arr[x,y-1] < 0):
            stack.append((x,y-1))

In [21]:
def find_index(bin_arr):
    cur_index = 1
    index_arr = np.ones(bin_arr.shape)*-1
    for i in range(0,bin_arr.shape[0]):
        for j in range (0,bin_arr.shape[1]):
            if index_arr[i,j] >=0:
                continue
            elif bin_arr[i,j] == 0:
                index_arr[i,j] = 0 
            else:
                dfs(bin_arr, index_arr, i,j, cur_index)
                cur_index = cur_index + 1
    return index_arr

In [23]:
index_arr = find_index(bin_arr)

In [38]:
print bin_arr
print index_arr

[[0 0 1 0 1]
 [1 1 1 0 0]
 [0 0 1 0 1]
 [1 1 0 0 1]]
[[ 0.  0.  1.  0.  2.]
 [ 1.  1.  1.  0.  0.]
 [ 0.  0.  1.  0.  3.]
 [ 4.  4.  0.  0.  3.]]


In [26]:
lin_size = index_arr.shape[0]*index_arr.shape[1]
lin_arr = np.reshape(index_arr,newshape=lin_size)

In [34]:
lin_arr

array([ 0.,  0.,  1.,  0.,  2.,  1.,  1.,  1.,  0.,  0.,  0.,  0.,  1.,
        0.,  3.,  4.,  4.,  0.,  0.,  3.])

In [35]:
output = []
count = 1
for i in range(0, lin_size):
    if (i < lin_size-1) and (lin_arr[i] == lin_arr[i+1]):
        count = count + 1
    else:
        output.extend([int(lin_arr[i]), int(count)])
        count = 1
print output

[0, 2, 1, 1, 0, 1, 2, 1, 1, 3, 0, 4, 1, 1, 0, 1, 3, 1, 4, 2, 0, 2, 3, 1]


In [7]:
def get_output_sequence(index_arr):
    


array([[-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.]])